/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['main.js']) {
  _$jscoverage['main.js'] = [];
  _$jscoverage['main.js'][1] = 0;
  _$jscoverage['main.js'][4] = 0;
  _$jscoverage['main.js'][5] = 0;
  _$jscoverage['main.js'][8] = 0;
}
_$jscoverage['main.js'][1]++;
var express = require("express"), app = express();
_$jscoverage['main.js'][4]++;
app.get("/", (function (req, res) {
  _$jscoverage['main.js'][5]++;
  res.send("Hello, Express!");
}));
_$jscoverage['main.js'][8]++;
module.exports = app;
_$jscoverage['main.js'].source = ["var express = require('express')","  , app = express()","","app.get('/', function (req, res) {","  res.send('Hello, Express!')","})","","module.exports = app"];
